### ISSUE TITLE
数据比例问题 1:1 数据流量问题

### ISSUE THREAD

**Issue by samac08** [rc452860/vnet#17]
1.节点比例不执行计算 ,实际按照1:1计算的 比例设置失效.
2. 感觉上传下载流量记录与实际用量 不准确
3.一直报不支持 startUDP: UDP CipherPacketDecorate init error: [SS Cipher] not support : rc4-md5-6 
4. 建议log参考v2版本v2ray-ssrpanel-plugin 添加 U/D 用量 log 显示 {newErrorf("+ %d users, - %d users, ↓ %s, ↑ %s, online %d",
			addedUserCount, deletedUserCount, bytefmt.ByteSize(downlinkTotal), bytefmt.ByteSize(uplinkTotal), onlineUsers).AtDebug().WriteToLog()}

**Comment by rc452860** [comment]
好的，最近我也是在看v2ray怎么写的。实际比例问题之前改过一次可能最近的一次bug修复又被我删掉了。我这次改完会着重测试一下这个点

**Comment by rc452860** [comment]
1. 节点费率计算只在更新user表`u`和`d`字段的时候计算流量 user_traffic_log未按照比率计算
2. 上传下载的记录与实际用量不准是因为加密会增加流量消耗流量记录测算的是解密之后的流量具体可以参照[shadowsocks.org](shadowsocks.org)中对于加密解密的描述，大部分加密头会混有iv另外aead加密方式会增加tag这样会导致流量和实际使用流量不符
3. 你加密方式肯定错了。本程序不支持rc4-md5-6加密方式。你赶紧查查数据库配置
4. 这个建议灰常不错。但是先让我研究研究。

**Comment by ssrpanel** [comment]
rc4 rc4-md5-6 已经被废弃了，

**Comment by ssrpanel** [comment]
@samac08 https://github.com/rc452860/vnet/issues/19

**Comment by rc452860** [comment]
@samac08 @ssrpanel 关于流量比例1:1 如果是指上报流量不准我需要更详细的信息，列如你们怎么统计流量不准的。上报流量和实际流量差多少。是否有开其他服务。

**Comment by samac08** [comment]
@rc452860  @ssrpanel  最新版问题更甚了 乘法好像变除法了 ?
<a href="https://imgchr.com/i/kZdVrd"><img src="https://s2.ax1x.com/2019/01/24/kZdVrd.md.png" alt="kZdVrd.png" border="0" /></a>

**Comment by rc452860** [comment]
这个计算规则有问题把。

**Comment by rc452860** [comment]
我已经在节点算过一次了

**Comment by samac08** [comment]
> 
> 
> 我已经在节点算过一次了

有问题 没有计算比例 ,最后还相除了

**Comment by rc452860** [comment]
你这个是面板显示问题找胖虎问一下？我上传u和d的时候已经乘过rate了

**Comment by samac08** [comment]
@rc452860 你可以看下我提这个回复 
https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/issues/11#issuecomment-451957848

**Comment by rc452860** [comment]
https://github.com/rc452860/vnet/blob/master/db/db.go#L327

**Comment by rc452860** [comment]
shit.那个总流量是胖虎算出来的。你找他。早知道我昨天就乘了。

**Comment by samac08** [comment]
> 
> 
> shit.那个总流量是胖虎算出来的。你找他。早知道我昨天就乘了。
不是那个是节点端算的 
U D不需要做运算 写入实用  仅总量那里做下比例计算 值写入总计这样即可  V2 ssrr都是这样的流程

**Comment by rc452860** [comment]
已经push了等ci自动编译完了重新下载v0.0.4试试把

**Comment by samac08** [comment]
> 
> 
> 已经push了等ci自动编译完了重新下载v0.0.4试试把  你可以参考下V2-go版本 最后的比例计算 修改的代码
https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/commit/327d4b038a13b582bb576c9632e44b4923c0bfe6

**Comment by samac08** [comment]
@rc452860 刚测试结果还是不计算

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/51656831-828ca680-1fdd-11e9-8626-b852b94b9df8.png)
哈哈哈哈哈哈。。。我一个不小心。

**Comment by samac08** [comment]
> 
> 
> @rc452860 刚测试结果还是不计算
> 
> ![image](https://user-images.githubusercontent.com/3949222/51656831-828ca680-1fdd-11e9-8626-b852b94b9df8.png)
> 哈哈哈哈哈哈。。。我一个不小心。
打住 ,实现方法有问题. 上/下不需要计算比例  就算最后的那个总的即可  Upload (original) + download (original) ={ total (upload + download) * Ratio } (Calculate and write table)

**Comment by rc452860** [comment]
是的啊，我只是写成了加号而已

**Comment by rc452860** [comment]
欸，项目其实是在gitlab上管理的。同步过来要等五分钟。

**Comment by samac08** [comment]
> 
> 
> 欸，项目其实是在gitlab上管理的。同步过来要等五分钟。
找到问题就好 你看下 下面图
ssrr 正常计算图
<img src="https://s2.ax1x.com/2019/01/07/FqVJiQ.png" alt="FqVJiQ.png" border="0">
V2-GO出现的最后一次计算问题 UD都计算后变成这个样子了  我提交了IS 最后一版 作者修正了问题. 现在完美.
<img src="https://s2.ax1x.com/2019/01/07/FqV8Ig.png" alt="FqV8Ig.png" border="0">

**Comment by rc452860** [comment]
好了编译通过了。欸主要是我还有其它几个项目在gitlab上。不然我就搬过来了。再下一次把这次99%没问题了

**Comment by ssrpanel** [comment]
@rc452860 我面板不需要改了吧，
感谢测试 @samac08

**Comment by rc452860** [comment]
@ssrpanel 不需要
