### ISSUE TITLE
ss_node 已加is_udp 字段用于节点使用允许走udp数据包

### ISSUE THREAD

**Issue by ssrpanel** [rc452860/vnet#24]
Commits 在此： https://github.com/ssrpanel/SSRPanel/commit/024a4fe74414e536a3cf786cd6bc9c34e72995b0

剩下靠你了。。大佬

**Comment by rc452860** [comment]
这个字段感觉我不好取这个玩意.你后台生成配置文件吧.我把配置加到了shadowsocks_options下有两个字段tcp_switch和udp_switch可以选择开启udp还是tcp

**Comment by ssrpanel** [comment]
好的，那我ss_node表的is_udp 仅做展示用

**Comment by rc452860** [comment]
@ssrpanel 你可以通过ss_noded is_udp来生成配置文件.我直接把udp和tcp都做成了配置.

**Comment by rc452860** [comment]
但是注意一下这个true是字符串需要用引号的

**Comment by rc452860** [comment]
0.0.5已经加上
