### ISSUE TITLE
config.json 加一个开关：是否优先走ipv6

### ISSUE THREAD

**Issue by ssrpanel** [rc452860/vnet#31]
当VPS有IPv6时，如果开启该选项，则默认走IPv6，未开启或者系统无IPv6 时则默认走IPv4
因为我在实测过程中发现，我的onevps都有ipv6，原本使用ssr是都可以看奈非，使用ip111.cn 检测时都是现实IPv4，但是用了vnet后，全部是IPv6地址，所以怀疑是因为IPv6导致某些目标网站无法访问

**Comment by rc452860** [comment]
已加
