### ISSUE TITLE
测试报告：too many colons in address

### ISSUE THREAD

**Issue by ssrpanel** [rc452860/vnet#35]
ERROR 2019-02-02 11:14:16 shadowsocks.go[234] 1: connect target:google.com:80 error cause: dial tcp: address 2607:f8b0:4007:804::200e:80: too many colons in address

**Comment by ssrpanel** [comment]
用的你刚才群里发的那个server

**Comment by ssrpanel** [comment]
我这台VPS 无IPV6

**Comment by rc452860** [comment]
你把ipv4_prefer设置成false

**Comment by rc452860** [comment]
优先解析ipv4

**Comment by rc452860** [comment]
0.0.5已解决
