### ISSUE TITLE
ERROR 2019-02-02 05:03:53 shadowsocks.go[232] 1: read target address error SOCKS error: 8. (maybe the crypto method 2rong configuration)

### ISSUE THREAD

**Issue by ntgeralt** [rc452860/vnet#37]
你好，我刚在GCP开了一台centos7执行
wget https://github.com/rc452860/vnet/releases/download/v0.0.4/vnet_linux_amd64 -O vnet &&chmod +x vnet
./vnet
最后刷出一堆端口。
然后客户端测试不联通。ssh提示read target address error SOCKS error: 8. (maybe the crypto method 2rong configuration)
我仔细看ssrpanel web加密方式aes-192-ctr/origin/plain，对应客户端是一致的。
请问一下是什么问题?ssrpanel 是18年12月是需要更新吗

**Comment by rc452860** [comment]
不支持ctr

**Comment by ssrpanel** [comment]
你得先装libsodium @ntgeralt

**Comment by ntgeralt** [comment]
最初提交这问题后，节点设置保持aes-192-ctr情况下，客户端改用none加密，竟然联通了;他好像是读取不到数据库的加密方式

**Comment by ntgeralt** [comment]
之前以为是读取节点信息写的加密方式，读取的是用户列表-代理信息里面加密方式。
