### ISSUE TITLE
测试报告：DNS解析异常

### ISSUE THREAD

**Issue by ssrpanel** [rc452860/vnet#39]
ERROR 2019-02-02 13:29:19 dns.go[53] MustReslove: dns can not reslove ip for domain: xxz8zewrkrakztxg.skt.ipip.net .
ERROR 2019-02-02 13:29:19 shadowsocks.go[229] 1: dns reslove error: xxz8zewrkrakztxg.skt.ipip.net .
ERROR 2019-02-02 13:29:21 dns.go[147] do: read udp 198.181.45.89:35095->8.8.4.4:53: i/o timeout
ERROR 2019-02-02 13:29:21 dns.go[53] MustReslove: dns can not reslove ip for domain: hg8ndwmnh3nbdfnj.skt.ipip.net .
ERROR 2019-02-02 13:29:21 shadowsocks.go[229] 1: dns reslove error: hg8ndwmnh3nbdfnj.skt.ipip.net .

开了全局，你群里给的新版 ，默认配置

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/52165361-dd8b6f80-273a-11e9-820f-0bb105888d24.png)
![image](https://user-images.githubusercontent.com/3949222/52165372-0dd30e00-273b-11e9-8bba-bceb99329f71.png)

**Comment by rc452860** [comment]
这两个奇怪的地址没有dns解析

**Comment by ssrpanel** [comment]
我也奇怪，你可以试一下windows下 全局模式 访问 ipip.net

**Comment by rc452860** [comment]
这个地址很奇怪估计ipip故意搞得
