### ISSUE TITLE
200k/s。。

### ISSUE THREAD

**Issue by mzfqy** [rc452860/vnet#41]
wget https://github.com/rc452860/vnet/releases/download/v0.0.5/vnet_linux_amd64 -O vnet && chmod +x vnet && ./vnet
两台服务器 HINET+AZ_HK
用这个搭建都是200k/s。。。

**Comment by ssrpanel** [comment]
限速单位已改，面板需要执行 php artisan upgradeUserSpeedLimit  对原有用户的限速字段数据进行升级，之前的是 204800 ，

**Comment by mzfqy** [comment]
了解。
