### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by ssrpanel** [rc452860/vnet#46]
````
ERROR 2019-02-19 12:59:16 shadowsocks.go[228] 1: connect target:ipv6.www.so.com:443 error cause: dial tcp [240e:83:201:110:36:110:234:123]:443: connect: no route to host

````

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/53385861-eb8b8380-39ba-11e9-9aeb-8f6d6bb4fee3.png)

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/53385887-fe05bd00-39ba-11e9-8347-999db05958f4.png)
