### ISSUE TITLE
数据读取与同步问题  限速模块

### ISSUE THREAD

**Issue by samac08** [rc452860/vnet#55]
SSRP面板修改限速后启动vnet 测试结果正确一致么有问题,但是后续再次修改限速放大限制后 再次测试还是上次的测试结果并不是最新的. .同步时钟设置的1分钟 ,2分钟后还是并没有读取最新的数据库信息限速也不起正确作用.只有再次重启vnet程序 结果才正常并且是最新的限制速度.

**Comment by ssrpanel** [comment]
目前还做不到面板修改了限速之后，vnet自动识别其限速值，这个确实值得改进，就很棒了，面板里就可以配合商品做带限速的商品了

**Comment by rc452860** [comment]
这个忘了改....上次胖虎说过.忘记了.
