### ISSUE TITLE
不能调用外部配置文件 ? 还是姿势不对 ?

### ISSUE THREAD

**Issue by samac08** [rc452860/vnet#59]
1.写好了系统服务守护进程 服务工作正常 现在有个问题 发现无法使用参数读取指定配置文件
例如 启动:
ExecStart=/usr/bin/vnet -c or -config  /etc/vnet/config.json 
2. log日志保存到文件及路径发现没有相关配置参数? config.json里面log参数配置怎么写?

**Comment by samac08** [comment]
@rc452860  期待大佬抽时间回复下怎么调用 配置文件  已经log保存参数
vnet.service demo:
[Unit]
Description=Vnet Service
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/run/vnet.pid
ExecStart=/usr/bin/vnet -c /etc/vnet/config.json OR -config /etc/vnet/config.json    ????????
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by rc452860** [comment]
emmm..这个功能缺失了.我周末给你补上.

**Comment by samac08** [comment]
> emmm..这个功能缺失了.我周末给你补上. @rc452860  好的谢谢  还有log输出文件位置参数最好是在config.json指定位置这样 期待更好的体验  尤其是单端口急需.
1. 这个 func formatLoad() string {
	return fmt.Sprintf("cpu:%v%% mem:%v%% disk:%v%%", service.GetCPUUsage(), service.GetMemUsage(), service.GetDiskUsage())
} 
能否改成 U: 10% R: (512M)-10%  N: 35.2↓-24.4↑ 绝大部分人不太关注磁盘基本不需要磁盘info可以忽略 毕竟很多就是小VPS主就搭桥 节点多了很容易观察内存情况(总内存)  节点多了单%还是不太好看要回想主机是多少ram或者以情况重启下 网络取网卡流量GB/TB这样

**Comment by ssrpanel** [comment]
> > emmm..这个功能缺失了.我周末给你补上. @rc452860  好的谢谢  还有log输出文件位置参数最好是在config.json指定位置这样 期待更好的体验  尤其是单端口急需.
> 
> 1. 这个 func formatLoad() string {
>    return fmt.Sprintf("cpu:%v%% mem:%v%% disk:%v%%", service.GetCPUUsage(), service.GetMemUsage(), service.GetDiskUsage())
>    }
>    能否改成 U: 10% R: (512M)-10%  N: 35.2↓-24.4↑ 绝大部分人不太关注磁盘基本不需要磁盘info可以忽略 毕竟很多就是小VPS主就搭桥 节点多了很容易观察内存情况(总内存)  节点多了单%还是不太好看要回想主机是多少ram或者以情况重启下 网络取网卡流量(RX bytes TX bytes)值 GB/TB这样 配合每月启动一次主机基本可以实现简单的主机流量统计了.

Panda Tom, [15.03.19 00:26]
这个建议改成：  CPU： MEMORY：  DISK： TX： RX：

Panda Tom, [15.03.19 00:26]
然后我面板里适配 这几个英文关键词

Panda Tom, [15.03.19 00:27]
我转换成中文

Panda Tom, [15.03.19 00:27]
它提的issues里貌似是要当前的上传流量和 下载流量，这个不好算吧

Panda Tom, [15.03.19 00:27]
读网卡的TX 和 RX也行啊

**Comment by samac08** [comment]
> > > emmm..这个功能缺失了.我周末给你补上. @rc452860  好的谢谢  还有log输出文件位置参数最好是在config.json指定位置这样 期待更好的体验  尤其是单端口急需.
> > 
> > 
> > 
> > 1. 这个 func formatLoad() string {
> >    return fmt.Sprintf("cpu:%v%% mem:%v%% disk:%v%%", service.GetCPUUsage(), service.GetMemUsage(), service.GetDiskUsage())
> >    }
> >    能否改成 U: 10% R: (512M)-10%  N: 35.2↓-24.4↑ 绝大部分人不太关注磁盘基本不需要磁盘info可以忽略 毕竟很多就是小VPS主就搭桥 节点多了很容易观察内存情况(总内存)  节点多了单%还是不太好看要回想主机是多少ram或者以情况重启下 网络取网卡流量(RX bytes TX bytes)值 GB/TB这样 配合每月启动一次主机基本可以实现简单的主机流量统计了.
> 
> Panda Tom, [15.03.19 00:26]
> 这个建议改成： CPU： MEMORY： DISK： TX： RX：
> 
> Panda Tom, [15.03.19 00:26]
> 然后我面板里适配 这几个英文关键词
> 
> Panda Tom, [15.03.19 00:27]
> 我转换成中文
> 
> Panda Tom, [15.03.19 00:27]
> 它提的issues里貌似是要当前的上传流量和 下载流量，这个不好算吧
> 
> Panda Tom, [15.03.19 00:27]
> 读网卡的TX 和 RX也行啊
@rc452860 @ssrpanel  直接读网卡的流量值就行 不需要计算  配合月初重启一次 一直不重启的话到月底自行计算下RX+TX就是实际消费流量,  另外面板也可以取节点的RX+TX做下计算下,配合主页的30内流量选项卡 点击后来个各节点统计表明细  各实际单月上传 /下载 消耗流量统计明细表 月末30号在计算所有 最后来个总合计 完美..  

<img src="https://s2.ax1x.com/2019/03/15/AEi2M8.png" alt="AEi2M8.png" border="0" />

**Comment by samac08** [comment]
@rc452860 @ssrpanel 节点统计明细表可以这样或者显示更多列相关信息...  
美国节点1  DDns否   IP: 114.114.114.114   在线 108人 流量3000GB  上传消耗 35.2↓    下载消耗  24.4↑    合计 :  78.6G 
美国节点2  DDns否   IP: 114.114.114.114   在线: 135人 流量5000GB  上传消耗 45.2↓    下载消耗  14.4↑    合计 :  59.6G

**Comment by ssrpanel** [comment]
其实我知道一个更骚的方法集成进面板，根本不需要你上报这些流量信息

**Comment by fyhqycom** [comment]
在
common/config/config.go

import "flag"
var (
	cfg = flag.String("cfg", "", "Config file for Manager.")
)
原有的 LoadDefault 修改为

func LoadDefault() (*Config, error) {
	flag.Parse()
	if *cfg != "" {
		return LoadConfig(*cfg)
	} else {
		return LoadConfig("config.json")
	}
}

**Comment by jarvanh** [comment]
我把指定配置文件加上了。
https://github.com/jarvanh/vnet/releases/tag/0.0.7

**Comment by rc452860** [comment]
@jarvanh 你可以提pull request.我可以合并进来.不过0.0.6已经算废弃了.只适用于ssrpanel老版本.

**Comment by jarvanh** [comment]
新版本闭源了，只能先用着老版本。

**Comment by ssrpanel** [comment]
> 我把指定配置文件加上了。
> https://github.com/jarvanh/vnet/releases/tag/0.0.7

给你点赞，有兴趣加入新协议研发吗
