### ISSUE TITLE
用户配资信息更改需vnet重启才能生效

### ISSUE THREAD

**Issue by hardywu** [rc452860/vnet#67]
用户更改加密模式，密码等，vnet需要重启才能生效。可以在用户建立链接的时候更新下配置数据。需要我来pr不？

**Comment by rc452860** [comment]
新版本使用api访问了。但是鉴于ssrpanel已经闭源。可能你需要去找一下胖虎。

**Comment by ssrpanel** [comment]
已经废弃db版了，全部走webapi了。。。
