### ISSUE TITLE
初次运行显示18000多天，怎么搞都不刷新啊？

### ISSUE THREAD

**Issue by Mr-Kwok** [rc452860/vnet#69]
初次运行显示18000多天，怎么搞都不刷新啊？
还有混淆协议什么的在哪设置啊？找不到配置文件啊！

**Comment by rc452860** [comment]
那可能是个bug,协议正在写.还没发.那个bug在obfs_tls混淆协议加入后我会来查.目前还没查到.偶尔会出现.

**Comment by Mr-Kwok** [comment]
原来是这样，还有节点状态能不能再下次更新时把硬盘信息改成节点当前带宽总占用率？或是其他比较有用的信息？

**Comment by rc452860** [comment]
你可能有那个的0.0.4版本，下0.0.6版本的。首页的说明没有更新，api版本已经测试完了。以后不会使用这种方式上报了。
