### ISSUE TITLE
混淆式单端口

### ISSUE THREAD

**Issue by yulewang** [rc452860/vnet#70]
期待能有混淆式单端口的支持，客户端可以有更多选择。

**Comment by rc452860** [comment]
混淆已经搞定了。api也接入完了。不过面板没有开源。你得去找胖虎。

**Comment by yulewang** [comment]
我的意思是利用v2ray-plugin或者simple obfs的混淆参数区分用户用来实现原版ss单端口多用户，毕竟各OS上支持ssr的客户端越来越没落。不知道是否好实现？

**Comment by ssrpanel** [comment]
@yulewang 不是没落了，而是护网行动，我们不当出头鸟。都在开发，不过我们都不吭声不放出来，小范围内分享
