### ISSUE TITLE
自行编译问题 

### ISSUE THREAD

**Issue by samac08** [rc452860/vnet#71]
尝试在window下编译 W/L 相同提示不能加载模块问题 编译不通过 

-------------------
build linux amd64
build command-line-arguments: cannot load gopkg.in/AlecAivazis/survey: cannot find module providing package gopkg.in/AlecAivazis/survey
done~

**Comment by rc452860** [comment]
gopkg的目录 请自备科学上网下载

**Comment by samac08** [comment]
> gopkg下的包 请自备科学上网下载
---------
以过桥了 好像资源有问题 你检查下

**Comment by rc452860** [comment]
那个资源确实有些问题。但是官网就是这样下载的。我之前也是手动拷贝的。不过这不重要了。我重构了一版说不定已经去掉了。

**Comment by rc452860** [comment]
https://github.com/AlecAivazis/survey

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/58534485-05d53780-821e-11e9-8f88-1ba58bd4f5e2.png)

**Comment by samac08** [comment]
@rc452860 
---------------
 我修改了下do.go里面的的链接为gopkg.in/AlecAivazis/survey.v1  编译测试ok 

-------------

Getting started
To get the package, execute:

go get gopkg.in/AlecAivazis/survey.v1
To import this package, add the following line to your code:

import "gopkg.in/AlecAivazis/survey.v1"
Refer to it as survey.

For more details, see the API documentation.

**Comment by samac08** [comment]
@rc452860  编译ok 运行测试OK  现在日志好像缺少模块 ??? 具体哪个?
INFO[0055] [123.117.000.000:64839 %!s(int=13506) tcp s.youtube.com:443] <----%!v(MISSING):%!s(MISSING)----> %!s(MISSING)
INFO[0065] [123.117.000.000:64841 %!s(int=13506) tcp www.googleapis.com:443] <----

**Comment by rc452860** [comment]
你编译的vnet_obfs分支？

**Comment by rc452860** [comment]
不是缺少组件，是缺少参数。

**Comment by samac08** [comment]
> 不是缺少组件，是因为参数为nil
哦确实obfs  我看你config 也没有obfs参数定义 具体应该怎么写 来个详细用法吧
---------------------
ERRO[0003] tcp:%v read target address error %s. (maybe the crypto method wrong configuration)[13506 SOCKS error: ErrAddressNotSupported]
ERRO[0008] tcp:%v read target address error %s. (maybe the crypto method wrong configuration)[13506 SOCKS error: ErrAddressNotSupported]
ERRO[0041] tcp:%v read target address error %s. (maybe the crypto method wrong configuration)[13506 SOCKS error: ErrAddressNotSupported]
ERRO[0044] tcp:%v read target address error %s. (maybe the crypto method wrong configuration)[13506 SOCKS error: ErrAddressNotSupported]

**Comment by rc452860** [comment]
我定义了一版新的api，通过api直接 读取面板上的节点配置信息。只需要配置api的地址节点的id和读取配置用的key就行了。编译脚本已经更新，windows上直接使用build.cmd就可以编译。vnet_obfs分支。具体请看api目录下的定义。文档后期放出。

**Comment by samac08** [comment]
@rc452860 编译测试通过。API的配置参数信息还是定义到cong.json里面兵并读取吧 ，还有auth_a 已经支持了 应该可以做链接限制了 请问限链接数数据库表字段参数现在怎么定义的值？配合下应该可以搞限线程的shop了 这下基本是完美了 ，还有v2ray插件的实现现阶段有计划否？

**Comment by rc452860** [comment]
没有v2ray实现计划.在研发新的客户端和协议.

**Comment by rc452860** [comment]
新版本已经实现了chain_auth_a aes128sha1 aes128md5  tls1.2_ticket_auth http_simple.不过没开源.如果新版协议研发出来就开源.
